# Libraries and Environment Modules {#libraries}

## Introduction

```{block, type='rmdcaution'}
Please note that RStudio Workbench is decoupled from Slurm.
Everything which should be run on the nodes via Slurm requires to have the respective env modules loaded in the Slurm template file whereas if you run something in RStudio server, the libraries installed in the underlying Ubuntu 20.04 container will be used.
```

The following part only deals with the Spack configuration side as everything in the container should just work (with respect to R).

Most system relevant libraries are installed via [Spack](spack.io).
However, as a user you do not need to worry about this since you are loading everything via "environment modules".
Available modules can be queried using `modules avail`.

For setup reasons, please put the following at the top of your `~/.bashrc` file

```sh
export SPACK_ROOT=/opt/spack
. $SPACK_ROOT/share/spack/setup-env.sh
```

Here is a snapshot:

```sh
------------------------- /opt/spack/share/spack/modules/linux-centos7-x86_64 --------------------------
   byobu-5.127-gcc-9.2.0-by2qc2g          (L)    python-3.7.4-gcc-9.2.0-nbjbfzi     (L)
   ccache-3.3.4-gcc-9.2.0-v3xzqqh         (L)    r-3.5.2-gcc-9.2.0-oxo76vo
   curl-7.63.0-gcc-9.2.0-cq4w37y          (L)    r-3.6.1-gcc-9.2.0-j25wr6z
   fish-3.0.0-gcc-9.2.0-gdyab6r      
```

## Loading modules

Modules can be loaded via `module load <module>`.

First, you need to load a C compiler as most programs depend on it.
This module is the only one that you should which uses `gcc-4.8.5`.
Make sure to also put this one into your `~/.bashrc` file!

```sh
module load gcc-9.2.0-gcc-4.8.5-wqdecm4
```

Now you can (for example) load GDAL:

```sh
module load gdal-2.4.2-gcc-9.2.0-henhg26
```

You can check that it worked via 

```sh
gdalinfo --version
```

## Checking loaded modules

```sh
module list
```

## Default modules

It is useful to have some modules loaded by default when logging in to the server.
Simply add them to `~/.bashrc`.

When running R for spatial analysis, the following are required:

```sh
module load \
  gcc-9.2.0-gcc-4.8.5-wqdecm4 \
  gdal-2.4.2-gcc-9.2.0-henhg26 \
  geos-3.7.2-gcc-9.2.0-jxq7o2n \
  git-2.21.0-gcc-9.2.0-o45v5mj \
  proj-5.2.0-gcc-9.2.0-5t4r5t4 \
  udunits2-2.2.24-gcc-9.2.0-hupsw3n \
  zlib-1.2.11-gcc-9.2.0-j3zdmzq
```

Furthermore, I recommend the following ones (don't forget to append your version and compiler):

```sh
byobu-5.127-gcc-9.2.0-x5e5mnz
git-2.21.0-gcc-9.2.0-hhkbkhg
ccache-3.3.4-gcc-9.2.0-7klqklq
python-3.7.4-gcc-9.2.0-nbjbfzi
curl-7.63.0-gcc-9.2.0-cq4w37y
```

You might wonder why you shouldn't add a R version to this list? Good question!

You can load an R module by default - just note that it will not have an effect on RStudio Workbench.
And for all Slurm project configurations you should specify which R version to use within the template itself and not rely on a default set somewhere.

## R

### SLURM

All versions from v3.4.4 upwards are installed.

To load a specific R version for Slurm usage, load the specific environment module

```sh
# loads R v3.5.2
module load r-3.5.2-gcc-9.2.0-oxo76vo
```

and then execute `R`.

You might find the following aliases helpful which you can put into `~/.bashrc`:

```sh
alias r344="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.4.4-hobcfrryiwu34etqvf4khv427wwkxdf5/rlib/R && radian"
alias r350="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.0-jx2cc3ecnk4zkfz3kqwomwsm5rpfouiv/rlib/R && radian"
alias r351="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.1-h4fvapuqf65avikja735xn5lzyildzzi/rlib/R && radian"
alias r352="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.2-oxo76vo5ceamc2qp6nfr6zvcqstvzksb/rlib/R && radian"
alias r353="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.3-a75bebsahiaaz6lrcdallnjprx3iybjv/rlib/R && radian"
alias r360="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.6.0-2sbeu7xbnocpahdm7afuonsumblmgi5j/rlib/R && radian"
alias r361="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.6.1-j25wr6zcofibs2zfjwg37357rjj26lqb/rlib/R && radian"
```

This enables you to launch the specific R version using the set command, e.g. `r360` will launch R v3.6.0.

**BLAS/LAPACK**

Unfortunately we cannot use an external BLAS/LAPACK like `openblas` due to the different architectures on the nodes.
When compiling R with the use of external BLAS/LAPACK, `openblas` tailors to the arch of the main node (threadripper) and specific processes (e.g. function from the `mgcv`) package will segfault

The use of the R internal BLAS/LAPACK comes with a substantial decrease in speed for numerical applications.

### RStudio Workbench

For RStudio Workbench, R interpreters are installed within the image.

## RStudio Workbench

RStudio Workbench is running on port 8787 (https://edi.geogr.uni-jena.de:8787) (legacy) and directly on https://edi.geogr.uni-jena.de/.

The service is running in a docker container (with Ubuntu 20.04 as the OS).
Hence, a new terminal will start a terminal with Ubuntu 20.04 as the underlying OS.
The service is decoupled from the CentOS host system.
Also the R interpreters are different to the ones used in Slurm jobs which are environment modules via Spack.

## Shiny Server

Shiny server is running on port 3838 with user support.
This means users can place apps in `$HOME/Shinyapps/` and they will be deployed as `http://edi.geogr.uni-jena.de:3838/<username>/<appname>`.

Note the `http` (`https` is only available in the Pro version).

Exemplary apps:

- http://edi.geogr.uni-jena.de:3838/patrick/hyperspectral/
- http://edi.geogr.uni-jena.de:3838/jannes/cluster_map/

## Libraries

If you cannot find a module you want to use, check it Spack supports it via `spack list <module>` and contact an admin to install it for you.
The following subsections refer to installations on the host, not RStudio Workbench.

### Docker

Docker is installed on the frontend only (for example to convert .html to .pdf).
To use `docker`, your user needs to be added to the "docker" group.
Please contact an Admin in case you want to use it.

### OSRM

[Open Source Routing Machine](https://github.com/Project-OSRM/osrm-backend) is installed.

Start the server with `osrm-routed`.  
More information can be found [here](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM).

### GDAL {#gdal}

Check `module avail` and look for GDAL to see which versions are available.

## Getting Started

If you worked through all these steps, you are almost good to go.
Here are have some further recommendations to make your life easier.

#### byobu

`byobu` is a wrapper for your SSH session that makes it possible to close your terminal session and not loose the command running in it.
If you start long running jobs, you can safely start them in a `byobu` window without worrying about them to quit once you shut down your machine.

Run `byobu` after being logged in and a `byobu` session will be launched.

You can open multiple ones with `byobu -S <session name>`, e.g. `byobu -S session2`.
Once you have multiple ones open, an interactive prompt will ask you which one you want to start next time.

#### radian {#radian}

`radian` is an optimized R command line tool. 
You will notice the benefits compared to the default `R` once you start using it.
You need to install it via `pip` which is already installed if you installed `python`.

Usually `setuptools` needs to be upgraded first.

```sh
pip install --user --upgrade setuptools
pip install --user radian
```

Now you can either always use `radian` or set an alias in your `.bashrc` , e.g. `alias r="radian"`.
Note that `radian` only works if you have set the env variable `R_HOME` correctly.
See [here](#R) for more details.

If is does not work at this moment, you might need to add the binary to your `$PATH` variable in your `~/.bashrc`.

```sh
export PATH=~/.local/bin:$PATH
```

#### ccache

If you load `ccache`, you will speed-up source installations of R packages a lot.
(On Linux, all R packages are installed from source.)
Besides loading `ccache`, you also need to create the following file in your home directory (`~/.R/Makevars`):

(Note that you need to create the folder first, it does not exist by default (`mkdir ~/.R/`).)

```sh
CXX_STD = CXX14

VER=
CCACHE=ccache
CC=$(CCACHE) gcc $(VER)
CXX=$(CCACHE) g++$(VER)
C11=$(CCACHE) g++$(VER)
C14=$(CCACHE) g++$(VER)
FC=$(CCACHE) gfortran$(VER)
F77=$(CCACHE) gfortran$(VER)
```

When installing a package now, you will occasionally see that the `gcc` lines are prefixed with `ccache`.
This means that this `gcc` call was already executed once and is now loaded from the cache rather than being run again.
This saves a lot of time, especially for packages that take long to install (`dplyr`, `Rcpp`, `stringi`).

#### Create a bash alias for your project {#wrapper}

Often you might want to use an {renv} library in a specific directory with a specific R version.
Rather than navigating there all the time by hand and loading the R version manually, you can create an alias that does this for you.
You can of course also use this approach without {renv}  - just to load a specific version. 

```
alias my-project="cd /path/to/project && <load custom env module> && r361"
```

Put this in your `.bashrc` and save time :)
